//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.ProductosdeVenta = new HashSet<ProductosdeVenta>();
        }
    

        public int idVenta { get; set; }
        [Required, StringLength(50, MinimumLength = 5)]
        public string usuario_vendedor { get; set; }
        [Required, StringLength(50, MinimumLength = 5)]

        public int cliente { get; set; }

    
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosdeVenta> ProductosdeVenta { get; set; }
    }
}
